parameters:
    app.pim_structure.config_path: '%kernel.project_dir%/config/resources/cloudinary/structure.yaml'
    app.dam_to_pim_mapping.config_path: '%kernel.project_dir%/config/resources/cloudinary/mapping.yaml'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    AkeneoDAMConnector\Infrastructure\DAM\Cloudinary\:
        resource: '../../src/Infrastructure/DAM/Cloudinary/*'

    AkeneoDAMConnector\Infrastructure\DAM\Cloudinary\Search:
        arguments:
            $cloudName: '%env(CLOUDINARY_CLOUD_NAME)%'
            $apiKey: '%env(CLOUDINARY_API_KEY)%'
            $apiSecret: '%env(CLOUDINARY_API_SECRET)%'

    AkeneoDAMConnector\Application\DamAdapter\FetchAssets: '@AkeneoDAMConnector\Infrastructure\DAM\Cloudinary\FetchAssets'
