services:
    AkeneoDAMConnector\Infrastructure\DAM\Cloudinary\:
        resource: '../../src/Infrastructure/DAM/Cloudinary/*'

    AkeneoDAMConnector\Infrastructure\DAM\Cloudinary\Search:
        arguments:
            $cloudName: '%env(CLOUDINARY_CLOUD_NAME)%'
            $apiKey: '%env(CLOUDINARY_API_KEY)%'
            $apiSecret: '%env(CLOUDINARY_API_SECRET)%'
