parameters:
    app.pim_structure.config_path: '%kernel.project_dir%/config/resources/fake/structure.yaml'
    app.dam_to_pim_mapping.config_path: '%kernel.project_dir%/config/resources/fake/mapping.yaml'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    AkeneoDAMConnector\Infrastructure\DAM\Fake\:
        resource: '../../src/Infrastructure/DAM/Fake/*'

    AkeneoDAMConnector\Application\DamAdapter\FetchAssets: '@AkeneoDAMConnector\Infrastructure\DAM\Fake\FetchAssets'
