services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  AkeneoDAMConnector\Infrastructure\DAM\Fake\:
    resource: '../../src/Infrastructure/DAM/Fake/*'

  AkeneoDAMConnector\Application\DamAdapter\FetchAssets: '@AkeneoDAMConnector\Infrastructure\DAM\Fake\FetchAssets'
